### PR TITLE
Update linux install instructions

### PR DESCRIPTION
**Pull request by robsontenorio**
There is no pecl extension available for `kafka`

```bash
No releases available for package "pecl.php.net/kafka"
```

### CODE REVIEW

**Comment by nick-zh** [comment]
@robsontenorio yeah sry, i added this a bit prematurely, i am still in touch with the php community to add it to PECL :smile: 
i will remove that for the time being, thx for the input :heart:

**Comment by robsontenorio** [comment]
@nick-zh 

Will pecl rdkafka be renamed to pecl kafka? Or they are different projects?

 I am getting started now. And that is a bit confusing.

**Comment by nick-zh** [comment]
These are different projects, i will follow a different philosophy than the original project and want to move faster
I am sorry for the confusion this is posing on you :bow:

**Comment by robsontenorio** [comment]
@nick-zh Maybe some footnotes about diferences between that libraries/ext/package would be useful for newcomers. 

Thanks for your helping!

**Comment by nick-zh** [comment]
Agreed, thank you for the input. I will add this tomorrow

**Pull request closed without merging**
